spring.application.name=Back

server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/gestionbudget
spring.datasource.username=itu
spring.datasource.password=itu

spring.jpa.hibernate.ddl-auto=update
